trigger: none

pool:
  name: Azure Pipelines

steps:
- task: UseDotNet@2
  displayName: 'Install .NET core sdk'
  inputs:
    packageType: 'sdk'
    version: '2.2.x'
- task: UseDotNet@2
  displayName: 'Set .NET Core version to use'
  inputs:
    packageType: 'sdk'
    version: '2.2.x'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
