pool:
  name: Azure Pipelines
  
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'DemdevsecopsOWASP'
    scanPath: '**/*'
    format: 'ALL'
    reportFilename: 'owaspinforme'
    warnOnCVSSViolation: true
    enableExperimental: true
    enableRetired: true
    enableVerbose: true
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'Demdevsecops-WhiteDemo'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar30'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'DemDevsecops'
    cliProjectName: 'DemDevsecops'
    cliSources: '.'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'
- task: SonarQubeAnalyze@5
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(TestProjects)'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="$(Agent.TempDirectory)/TestResults/"'

- script: 'dotnet tool install -g dotnet-reportgenerator-globaltool'
  displayName: 'Install Report Generator Tool'

- script: 'reportgenerator "-reporttypes:Cobertura" "-reports:$(Agent.TempDirectory)/TestResults/coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)/coverlet/reports"'
  displayName: 'Merge code-coverage files'

- task: PublishCodeCoverageResults@1
  displayName: 'Generate code-coverage HTML report'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml'
    failIfCoverageEmpty: true

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
